# Generated by Django 4.2.7 on 2023-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='received_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
