# Generated by Django 4.2.7 on 2023-11-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0005_expenserecord_remove_productionrecord_accessories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseRecord',
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='received_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
