# Generated by Django 4.2.7 on 2023-11-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0008_alter_expense_accessories_alter_expense_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='model_name',
            field=models.CharField(default='default_value', max_length=30),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
