# Generated by Django 4.2.7 on 2023-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0009_expense_model_name_alter_productionrecord_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='model_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
