# Generated by Django 4.2.7 on 2023-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0010_alter_expense_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowFactoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('model', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('received_by', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
