# Generated by Django 4.2.7 on 2023-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0011_windowfactoryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('window_model_name', models.CharField(max_length=255)),
                ('glass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fittings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
