# Generated by Django 4.2.7 on 2023-11-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_records', '0012_windowexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowexpense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='windowexpense',
            name='fittings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='windowexpense',
            name='frame',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='windowexpense',
            name='glass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='windowexpense',
            name='installation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='windowexpense',
            name='other',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='windowexpense',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
