# Generated by Django 4.2.7 on 2023-11-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0014_profile_hobby_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
