# Generated by Django 4.2.7 on 2023-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0015_alter_productionrecord_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10),
        ),
    ]
