# Generated by Django 4.2.7 on 2023-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0016_alter_productionrecord_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fabric',
            field=models.IntegerField(blank=True, default='', max_length=30, null=True),
        ),
    ]
