# Generated by Django 4.2.7 on 2023-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0018_alter_expense_accessories_alter_expense_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name_fabric',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
