# Generated by Django 4.2.7 on 2023-12-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0019_expense_name_fabric_alter_expense_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
