# Generated by Django 4.2.7 on 2023-12-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0020_expense_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='comments',
        ),
    ]
