# Generated by Django 4.2.7 on 2023-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0022_alter_expense_accessories_alter_expense_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
