# Generated by Django 4.2.7 on 2023-12-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0023_expense_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
