# Generated by Django 4.2.7 on 2023-12-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_records', '0025_remove_expense_comments_expense_accessories_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='accessories_comment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fabric_comment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='model_name_comment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name_fabric_comment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='other_comment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='sewing_comment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='threads_comment',
        ),
    ]
